# Generated by Django 4.1.3 on 2022-12-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("facebook_link", models.URLField(blank=True, max_length=255)),
                ("twitter_link", models.URLField(blank=True, max_length=255)),
                ("google_link", models.URLField(blank=True, max_length=255)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name": "Team", "verbose_name_plural": "Teams",},
        ),
    ]
