# Generated by Django 4.1.3 on 2022-12-06 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_contact_uuid"),
    ]

    operations = [
        migrations.RemoveField(model_name="contact", name="id",),
        migrations.AlterField(
            model_name="contact",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
