# Generated by Django 4.1.3 on 2022-12-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_remove_contact_id_alter_contact_uuid"),
    ]

    operations = [
        migrations.RenameField(model_name="contact", old_name="uuid", new_name="id",),
    ]
