# Generated by Django 4.1.3 on 2022-12-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_rename_teams_team_alter_team_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="facebook_link",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="team",
            name="google_link",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="team",
            name="twitter_link",
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
