# Generated by Django 4.1.3 on 2022-12-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_team_facebook_link_alter_team_google_link_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Team",),
    ]
