# Generated by Django 4.1.3 on 2022-12-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="doors",
            field=models.CharField(
                choices=[("2", "2"), ("3", "3"), ("4", "4"), ("5", "5"), ("6", "6")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="car", name="fuel_type", field=models.CharField(max_length=50),
        ),
    ]
