# Generated by Django 4.1.3 on 2022-12-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_alter_car_created_date_alter_car_doors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
