# Generated by Django 4.1.3 on 2022-12-03 13:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_alter_car_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car", name="descrition", field=ckeditor.fields.RichTextField(),
        ),
    ]
