# Generated by Django 4.1.3 on 2022-12-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0009_alter_car_features"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car", old_name="descrition", new_name="description",
        ),
    ]
